name: PersonalYoga
favicon: null
layout_spectrum: 0.5582238270435482
typography_spectrum: 0.6360404430888593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8124112256336957
  lightness: 0.8992880173027515
  saturation: 0.18301010760478675
  rhythmicContrast: 0.7132018723059446
purpose: []
